### ISSUE TITLE
Migrate to carpentries org

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/instructor-training-bonus-modules#24]
As this content is official Carpentries material, it should be hosted in the Carpentries GH org. @maneesha - could you please migrate the content with the same access rights and set up a redirect? @klbarnes20 has confirmed there are no active bonus modules happening or scheduled for the near future, so safe to do this migration. 🙂

**Comment by maneesha** [comment]
I can transfer this repo to the `carpentries` organization.
@fmichonneau  Can you confirm that [this](https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7) would be the best way to ensure the redirect works? (so we'd still have a `instructor-training-bonus-modules` repo in the `carpentries-incubator` organization, with just one page that does the redirect)

**Comment by maneesha** [comment]
I spoke with @fmichonneau  who said this would work but would not be ideal. He will be working with @ErinBecker  on what we should do.

**Comment by fmichonneau** [comment]
The transfer is complete. If you work on this repository, make sure you update your remotes. For instance, if this remote is called 'origin' and you use https to connect to your repositories:

```
git remote set-url origin https://github.com/carpentries/instructor-training-bonus-modules.git
```
