### ISSUE TITLE
Should the "A Few Notes on Cloud Instances" be a call out?

### ISSUE THREAD

**Issue by sstevens2** [carpentries/instructor-training-bonus-modules#29]
The "A Few Notes on Cloud Instances" section does feel sort of out of place but maybe we could keep it as a callout (then seen as optional) in the lesson?  What do others think?

**Comment by karenword** [comment]
This was addressed in https://github.com/carpentries/instructor-training-bonus-modules/pull/32/files
Thanks @sstevens2 !
