### ISSUE TITLE
Prereqs?

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/instructor-training-bonus-modules#5]
In PR #4, I assumed no pre-reqs for this lesson. However, its possible that I'm wrong and there is some setup learners need to do. In particular, I know that people can connect to a Zoom call without installing anything, but I don't know if the same is true for using host and co-host features. 

Also not sure whether there are any required pre-readings for this lesson.

**Comment by karenword** [comment]
I don't think there are any technical prerequisites -- as far as I can tell the browser version does does allow most if not all features of interest to be used, and it may actually be instructive to have people join in this way. However, all modules will be targeting certified Carpentries Instructors, so I will close your PR and replace it with text to that effect. Thanks for pointing me at this section!
