### ISSUE TITLE
Transition to the Workbench

### ISSUE THREAD

**Issue by zkamvar** [carpentries/instructor-training-bonus-modules#55]
This lesson will be converted to use [The Carpentries Workbench][workbench]
To prevent accidental reversion of the changes, we are temporarily revoking
write access for all collaborators on this lesson:

 - [x] @klbarnes20 
 - [x] @karenword 

If you no longer wish to have write access to this repository, you do not
need to do anything further.

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
2. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
3. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

If you wish to regain write access, please re-clone the repository on your machine and
then comment here with `I am ready for write access :rocket:` and the
admin maintainer of this repository will restore your permissions.

If you have any questions, please reply here and tag @zkamvar

[workbench]: https://carpentries.github.io/workbench

**Comment by zkamvar** [comment]
The deed is done. The infrastructure takes a few minutes to bootstrap and cache the packages for the lesson build. Once the build is done, I will switch github pages to deploy from the `gh-pages` branch and you will have your workbench lesson. 

Thank you all for your enthusiasm and your patience!

**Comment by zkamvar** [comment]
The Workbench version is now live: https://carpentries.github.io/instructor-training-bonus-modules/

In addition, here is [map of commits that were changed during the transition](https://github.com/carpentries/lesson-transition/blob/release_cp/instructor-training-bonus-modules/release/carpentries/instructor-training-bonus-modules-commit-map.hash)

**Comment by klbarnes20** [comment]
Thanks @zkamvar!

**Comment by zkamvar** [comment]
@klbarnes20, would you say `I am ready for write access :rocket:`?

**Comment by klbarnes20** [comment]
Yes! Sorry again! I am ready for write access 🚀

**Comment by zkamvar** [comment]
granted!

**Comment by karenword** [comment]
I am ready for write access :rocket:

**Comment by zkamvar** [comment]
granted! Congratulations on your workbench lesson!
